default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: docker_example_dev

development:
  <<: *default
  database: cicle_ci_dev2

test:
  <<: *default
  database: cicle_ci_test

production:
  <<: *default
  username: whyme
#  database: your_production_db_name #CHANGE ME
